---
title: "Course Schedule"
---

This page includes schedule for the Fall 2025 semester, along with all the assigned readings and graded events.

*OpenIntro Statistics* and *Introduction to Modern Statistics* are both available as a free e-book. They can be downloaded from the links in the course letter, or they can be found in the course Teams page.

## Block 1: Probability Models

+--------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------------------------------------------------------------------------------+
| Lesson | Topic                                | BEFORE Class                                                                                                                                                                                                                     | AFTER Class | Graded Events (due dates)                                                                 |
+========+======================================+==================================================================================================================================================================================================================================+=============+===========================================================================================+
| 1      | Intro to Generative AI               |                                                                                                                                                                                                                                  | -   GPset 1 |                                                                                           |
+--------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------------------------------------------------------------------------------+
| 2      | Intro to Probability                 | -   READ: Section 3.1 Defining Probability, *OpenIntro Statistics*                                                                                                                                                               | -   GPset 2 | -   Strengths Activity                                                                    |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      | -   [Reading Guide for Lesson 2](https://notebooklm.google.com/notebook/3233b224-a086-4aeb-8bb5-1412444f7ee9){target="_blank"}                                                                                                   |             |                                                                                           |
+--------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------------------------------------------------------------------------------+
| 3      | Conditional Probability, Bayes' Rule | -   READ: Section 3.2 Conditional Probability, *OpenIntro Statistics*                                                                                                                                                            | -   GPset 3 | -   [Project Group Form](https://forms.office.com/r/W2MMh9jDyV){target="_blank"}          |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      | -   [Reading Guide for Lesson 3](https://notebooklm.google.com/notebook/06a6c546-6916-40cb-a710-a469f0842121){target="_blank"}                                                                                                   |             |                                                                                           |
+--------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------------------------------------------------------------------------------+
| 4      | Discrete Random Variables            | -   READ:                                                                                                                                                                                                                        | -   GPset 4 | -   HW 1                                                                                  |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      |     -   Section 10.2 Random variables (Intro through 10.2.4), [*Computational Probability and Statistics*](https://ds-usafa.github.io/Quarto-Book/Discrete-Random-Variables.html){target="_blank"}                               |             |                                                                                           |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      |     -   Section 3.4 (Intro through 3.4.2) Random Variables, *OpenIntro Statistics*                                                                                                                                               |             |                                                                                           |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      | -   [Reading Guide for Lesson 4](https://notebooklm.google.com/notebook/08abf03d-1d2d-4f78-9447-7c1d115dbf69){target="_blank"}                                                                                                   |             |                                                                                           |
+--------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------------------------------------------------------------------------------+
| 5      | Continuous Random Variables          | -   READ:                                                                                                                                                                                                                        | -   GPset 5 | -   [Pre-course AI questionnaire](https://forms.office.com/r/eCQCP9BLFa){target="_blank"} |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      |     -   Section 11.2 Continuous random variables (Intro through 11.2.2) and 11.3 Moments, [*Computational Probability and Statistics*](https://ds-usafa.github.io/Quarto-Book/Continuous-Random-Variables.html){target="_blank"} |             |                                                                                           |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      |     -   Section 3.5 Continuous distributions, *OpenIntro Statistics*                                                                                                                                                             |             |                                                                                           |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      | -   [Reading Guide for Lesson 5](https://notebooklm.google.com/notebook/c18d08c7-f192-4790-96ec-fd32137e30e8){target="_blank"}                                                                                                   |             |                                                                                           |
+--------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------------------------------------------------------------------------------+
| 6      | Named Distributions                  | -   READ: Sections 4.2 Geometric distribution, 4.3 Binomial distribution (through 4.3.1), and 4.5 Poisson distribution, *OpenIntro Statistics*                                                                                   | -   GPset 6 | -   Project Individual Task #1                                                            |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      | -   [Reading Guide for Lesson 6](https://notebooklm.google.com/notebook/5aeb5c88-de9a-435b-b93f-4d3a6481e74c){target="_blank"}                                                                                                   |             |                                                                                           |
+--------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------------------------------------------------------------------------------+
| 7      | Normal Distribution                  | -   READ:                                                                                                                                                                                                                        | -   GPset 7 | -   HW 2                                                                                  |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      |     -   Section 4.1 Normal Distribution, *OpenIntro Statistics*                                                                                                                                                                  |             |                                                                                           |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      |     -   [Section 13.2.2 Exponential distribution](https://ds-usafa.github.io/Quarto-Book/Named-Continuous-Distributions.html#exponential-distribution){target="_blank"} from *Computational Probability and Statistics*          |             |                                                                                           |
|        |                                      |                                                                                                                                                                                                                                  |             |                                                                                           |
|        |                                      | -   [Reading Guide for Lesson 7](https://notebooklm.google.com/notebook/3e74f22c-0af6-4afe-b5e7-d771b0a01990){target="_blank"}                                                                                                   |             |                                                                                           |
+--------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------------------------------------------------------------------------------------+

## Block 2: Data Wrangling and Visualization

+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| Lesson | Topic                              | BEFORE Class                                                                                                                                                                                                                                                                                                                                                   | AFTER Class                        | Graded Events (due dates)      |
+========+====================================+================================================================================================================================================================================================================================================================================================================================================================+====================================+================================+
| 8      | Data Basics                        | -   READ:                                                                                                                                                                                                                                                                                                                                                      | -   GPset 8                        |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   Chapter 1 Hello data from *Introduction to Modern Stats* *(2e)*                                                                                                                                                                                                                                                                                        |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   Chapter 5 Exploring numerical data from *Introduction to Modern Stats* *(2e)*                                                                                                                                                                                                                                                                          |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   [Reading Guide for Lesson 8](https://notebooklm.google.com/notebook/6f92eaad-f39d-44fa-802a-fc4496e533ea){target="_blank"}                                                                                                                                                                                                                                 |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 9      | GR1                                | Study! Practice!                                                                                                                                                                                                                                                                                                                                               | Relax!                             |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 10     | Data Collection and Studies        | -   READ: Chapter 2 Study design from *Introduction to Modern Stats (2e)*                                                                                                                                                                                                                                                                                      | -   GPset 10                       |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   [Reading Guide for Lesson 10](https://notebooklm.google.com/notebook/725f1277-edc9-4935-800d-01e8d6eb4b25){target="_blank"}                                                                                                                                                                                                                                |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 11     | Tidy Data                          | -   READ: [Chapter 4 Data Importing and Tidy Data](https://moderndive.com/v2/tidy.html){target="_blank"} from *Modern Dive*                                                                                                                                                                                                                                    | -   GPset 11                       | -   Project Group Task #1      |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   [Reading Guide for Lesson 11](https://notebooklm.google.com/notebook/c15d1e56-d2a1-42f9-9cc3-174b52c7ebe6){target="_blank"}                                                                                                                                                                                                                                |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 12     | Data Wrangling                     | -   READ: [Chapter 3 Data Wrangling](https://moderndive.com/v2/wrangling.html){target="_blank"} from *Modern Dive*                                                                                                                                                                                                                                             | -   GPset12                        | -   HW 3                       |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   [Reading Guide for Lesson 12](https://notebooklm.google.com/notebook/f3226153-1b7b-4766-af0f-bd472099e7fb){target="_blank"}                                                                                                                                                                                                                                |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 13     | Numerical Summaries                | -   READ: Chapter 5 Exploring Numerical Data from *Introduction to Modern Statistics* - beginning through Section 5.6                                                                                                                                                                                                                                          | -   GPset13                        |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   Complete the interactive lab, [Exploratory Data Analysis: 3 - Numerical Summaries](https://openintro.shinyapps.io/ims-02-explore-03/){target="_blank"} from *Introduction to Modern Statistics*                                                                                                                                                            |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   [Reading Guide for Lesson 13](https://notebooklm.google.com/notebook/71ff8b24-dce4-48e0-8ada-a497edc42929){target="_blank"}                                                                                                                                                                                                                                |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 14     | Data Visualization in 2D           | -   READ: [Chapter 2 Data Visualization](https://moderndive.com/v2/viz.html){target="_blank"} from *Modern Dive*                                                                                                                                                                                                                                               | -   GPset14                        |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   [Reading Guide for Lesson 14](https://notebooklm.google.com/notebook/1b0e9821-3ed8-4e1c-8394-e6a0160d2cd5){target="_blank"}                                                                                                                                                                                                                                |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 15     | Data Visualization in 1D           | -   READ: Chapter 6 Applications: Explore from *Introduction to Modern Statistics*                                                                                                                                                                                                                                                                             | -   GPset15                        | -   Project Individual Task #2 |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   Complete TWO interactive labs from *Introduction to Modern Statistics*:                                                                                                                                                                                                                                                                                    |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   [Exploratory Data Analysis: 1 - Exploring categorical data](https://openintro.shinyapps.io/ims-02-explore-01/){target="_blank"}                                                                                                                                                                                                                        |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   [Exploratory Data Analysis: 2 - Exploring numerical data](https://openintro.shinyapps.io/ims-02-explore-02/){target="_blank"}                                                                                                                                                                                                                          |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   Reading Guide for Lesson 15 (Gradescope only, no NotebookLM)                                                                                                                                                                                                                                                                                               |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 16     | Centrality and Spread              | -   READ:                                                                                                                                                                                                                                                                                                                                                      | -   GPset16                        | -   HW 4                       |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   Find examples of news articles, social media headlines, briefings, or official USAFA or CW communication where statistics "pop" up. Is there a moment when you suspect the communication is referring to a mean or a median? Are there references to "spread"? If so, what kind? What data visualizations did you encounter?                           |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   Look for examples of/references to measures of centrality in a news article, social media post, briefing, or official USAFA communication.                                                                                                                                                                                                         |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   Look for examples of/references to measures of spread in a news article, social media post, briefing, or official USAFA communication.                                                                                                                                                                                                             |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   Look for data visualizations in a news article, social media post, briefing, or official USAFA communication.                                                                                                                                                                                                                                      |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   Complete the interactive lab, [Exploratory Data Analysis: 4 - Case study](https://openintro.shinyapps.io/ims-02-explore-04) from *Introduction to Modern Statistics*                                                                                                                                                                                   |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   Reading Guide for Lesson 16 (Gradescope only, no NotebookLM)                                                                                                                                                                                                                                                                                               |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 17     | Data Provenance / History of Stats | -   READ:                                                                                                                                                                                                                                                                                                                                                      | -   GPset17 (due before Lesson 19) |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   Azar, B. (2010, May 1). Are your findings 'WEIRD'? *Monitor on Psychology*, *41*(5). <https://www.apa.org/monitor/2010/05/weird> (\~2 minute read)                                                                                                                                                                                                     |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   OPTIONAL: Original study can be found here: Henrich J, Heine SJ, Norenzayan A. The weirdest people in the world? *Behavioral and Brain Sciences*. 2010;33(2-3):61-83. [doi:10.1017/S0140525X0999152X](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences/article/weirdest-people-in-the-world/BF84F7517D56AFF7B7EB58411A554C17) |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         AND                                                                                                                                                                                                                                                                                                                                                    |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   **Choose ONE of the following to watch**. Feel free to watch on a faster speed, but please engage with the material in a meaningful way:                                                                                                                                                                                                               |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   [TED Talk](https://www.youtube.com/watch?v=_2u_eHHzRto){target="_blank"} by Cathy O'Neil, "The era of blind faith in big data must end":                                                                                                                                                                                                           |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   Introduction to the "Gender Shades" [study](https://www.youtube.com/watch?v=TWWsW1w-BVo){target="_blank"}                                                                                                                                                                                                                                          |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |             -   Associated [paper](https://proceedings.mlr.press/v81/buolamwini18a/buolamwini18a.pdf) for those interested                                                                                                                                                                                                                                     |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   [Summary video](https://www.youtube.com/watch?v=aZarigloqXc){target="_blank"} of the "Man is to Computer Programmer as Woman is to Homemaker" study:                                                                                                                                                                                               |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |             -   Associated [paper](https://proceedings.neurips.cc/paper_files/paper/2016/file/a486cd07e4ac3d270571622f4f316ec5-Paper.pdf) for those interested                                                                                                                                                                                                 |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         AND                                                                                                                                                                                                                                                                                                                                                    |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |     -   **Choose ONE of the following to read**. We know some of these are a bit long, but please engage with the material in a meaningful way! Feel free to utilize NotebookLM/ChatGPT for help in reading one of these articles:                                                                                                                             |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   Evans, Richard J. 2020. “RA Fisher and the Science of Hatred.” 28 July 2020. *New Statesman*. <https://www.newstatesman.com/long-reads/2020/07/ra-fisher-and-science-hatred>.                                                                                                                                                                      |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   Langkjaer-Bain, Robert. 2019. “The Troubling Legacy of Francis Galton.” June 2019. *Significance*. <https://doi.org/10.1111/j.1740-9713.2019.01275.x>.                                                                                                                                                                                             |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    |         -   Levy, Ido. 2019. “Eugenics and the Ethics of Statistical Analysis.” 16 December 2019. *Georgetown Public Policy Review*. <https://gppreview.com/2019/12/16/eugenics-ethics-statistical-analysis/>.                                                                                                                                                 |                                    |                                |
|        |                                    |                                                                                                                                                                                                                                                                                                                                                                |                                    |                                |
|        |                                    | -   Reading Guide for Lesson 17 (Gradescope only, no NotebookLM)                                                                                                                                                                                                                                                                                               |                                    |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+
| 18     | GR2                                | Study! Practice!                                                                                                                                                                                                                                                                                                                                               | Relax!                             |                                |
+--------+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+--------------------------------+

## Block 3: Inference

+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| Lesson  | Topic                                           | BEFORE Class                                                                                                                                                                           | AFTER Class                                                                  | Graded Events (due dates)      |
+=========+=================================================+========================================================================================================================================================================================+==============================================================================+================================+
| 19      | Sampling Framework                              | -   READ: [Chapter 7 Sampling from *Modern Dive*](https://moderndive.com/v2/sampling.html) - skip Section 7.3 but read the rest of the chapter                                         | -   GPset 19                                                                 | -   Project Group Task #2      |
|         |                                                 |                                                                                                                                                                                        | -   Course Participation Medal [form](https://forms.office.com/r/pqey5NwStW) |                                |
|         |                                                 | -   [Reading Guide for Lesson 19](https://notebooklm.google.com/notebook/90e79303-bb46-482e-a2fb-a8f5e4c1d320){target="_blank"}                                                        |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 20      | Bootstrap and Resampling                        | -   READ:                                                                                                                                                                              | -   GPset 20                                                                 |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   [Chapter 8 Estimation, Confidence Intervals and Bootstrapping](https://moderndive.com/v2/confidence-intervals.html){target="_blank"} from *ModernDive*                         |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Read the start of the chapter through the end of Section 8.1.1                                                                                                             |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Read Section 8.2 through the end of Section 8.2.1                                                                                                                          |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 12 Confidence intervals with bootstrapping from *Introduction to Modern Statistics (2e)*                                                                               |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Read the start of the chapter through the end of Section 12.1                                                                                                              |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 | -   [Reading Guide for Lesson 20](https://notebooklm.google.com/notebook/dbe1bbf8-4bbd-43ec-a956-a51d8cbf8c2c){target="_blank"}                                                        |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 21      | Confidence Intervals                            | -   READ:                                                                                                                                                                              | -   GPset 21                                                                 |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   [Chapter 8 Estimation, Confidence Intervals and Bootstrapping](https://moderndive.com/v2/confidence-intervals.html){target="_blank"} from *ModernDive*                         |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Sections 8.1.2 and 8.1.3                                                                                                                                                   |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Sections 8.2.2, 8.2.3, and 8.2.4                                                                                                                                           |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 12 Confidence intervals with bootstrapping from *Introduction to Modern Statistics (2e)*                                                                               |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Sections 12.2 through 12.4                                                                                                                                                 |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 | -   [Reading Guide for Lesson 21](https://notebooklm.google.com/notebook/2295503e-94b5-48ae-a2e7-ef6559c055df){target="_blank"}                                                        |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 22      | Interpreting Confidence Intervals               | -   READ:                                                                                                                                                                              | -   GPset 22                                                                 | -   HW 5                       |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   [Chapter 8 Estimation, Confidence Intervals and Bootstrapping](https://moderndive.com/v2/confidence-intervals.html){target="_blank"} from *ModernDive*                         |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Section 8.1.5 and Section 8.4 through the end of the chapter                                                                                                               |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 | -   [Reading Guide for Lesson 22](https://notebooklm.google.com/notebook/cab5ceee-5461-4999-888d-5af5993dc4cd){target="_blank"}                                                        |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 23      | Null and Alternative Hypotheses, p-values       | -   READ: Chapter 11 Hypothesis Testing with Randomization from *Introduction to Modern Statistics (2e)*                                                                               | -   GPset 23                                                                 |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 | -   [Reading Guide for Lesson 23](https://notebooklm.google.com/notebook/ea0504e3-9e9e-48be-992e-23e0286870f3){target="_blank"}                                                        |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 24      | Hypothesis Testing (difference of proportions)  | -   READ:                                                                                                                                                                              | -   GPset 24                                                                 |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 11 Hypothesis Testing with Randomization from *Introduction to Modern Statistics (2e)* - YES, read it again!                                                           |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 17 Inference for comparing two proportions from *Introduction to Modern Statistics (2e)*                                                                               |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Sections 17.1 and 17.2 only                                                                                                                                                |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 | -   [Reading Guide for Lesson 24](https://notebooklm.google.com/notebook/cc44a0ef-6741-412e-a8b1-ddd46ac043c9){target="_blank"}                                                        |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 25      | Hypothesis Testing (single mean and proportion) | -   READ:                                                                                                                                                                              | -   GPset 25                                                                 | -   Project Individual Task #3 |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 16 Inference for a Single Proportion from *Introduction to Modern Statistics (2e)*                                                                                     |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Beginning of the chapter through section 16.1                                                                                                                              |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 19 Inference for a Single Mean from *Introduction to Modern Statistics (2e)*                                                                                           |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Beginning of the chapter through section 19.1                                                                                                                              |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 11 Hypothesis Testing with Randomization from *Introduction to Modern Statistics (2e)* - continue to review!                                                           |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 | -   [Reading Guide for Lesson 25](https://notebooklm.google.com/notebook/69148b11-0d71-4196-9acb-eb9bd975fdb1){target="_blank"}                                                        |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 26      | Type I & II errors, Significance                | -   READ:                                                                                                                                                                              | -   GPset 26                                                                 | -   HW 6                       |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 14 Decision Errors from *Introduction to Modern Statistics (2e)*                                                                                                       |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |         -   Sections 14.0 through 14.5                                                                                                                                                 |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   [The ASA Statement on p-values: Context, Process, and Purpose](https://amstat.tandfonline.com/doi/epdf/10.1080/00031305.2016.1154108?needAccess=true){target="_blank"} article |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Chapter 11 Hypothesis Testing with Randomization from *Introduction to Modern Statistics (2e)* - continue to review!                                                           |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 | -   [Reading Guide for Lesson 26](https://notebooklm.google.com/notebook/b824b17f-001f-47be-a0c9-503cd92b0175){target="_blank"}                                                        |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 27      | Project - Mentor and Peer Feedback Day          | -   Make sure you have your group's mentor feedback ready to use in-class on Lesson 27                                                                                                 |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 |     -   Come to class prepared to review other groups' projects and provide feedback                                                                                                   |                                                                              |                                |
|         |                                                 |                                                                                                                                                                                        |                                                                              |                                |
|         |                                                 | -   NO Reading Guide                                                                                                                                                                   |                                                                              |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+
| 28      | GR3                                             | Study! Practice!                                                                                                                                                                       | Relax!                                                                       |                                |
+---------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------+--------------------------------+

## Block 4: Linear Regression

+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson | Topic                                                | BEFORE Class                                                                                                                                                                                                                 | AFTER Class  | Graded Events (due dates)                                                                                                                                                                         |
+========+======================================================+==============================================================================================================================================================================================================================+==============+===================================================================================================================================================================================================+
| 29     | Linear Regression and Correlation                    | -   READ:                                                                                                                                                                                                                    | -   GPset 29 |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 7 Linear regression with a single predictor from *Introduction to Modern Statistics (2e)*                                                                                                                    |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Beginning of the chapter through the end of Section 7.2                                                                                                                                                          |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   SKIP Section 7.1.3 Residuals                                                                                                                                                                                     |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   SKIP Section 7.2.4-7.2.5                                                                                                                                                                                         |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 29](https://notebooklm.google.com/notebook/5c4013fc-79f7-4c55-b7b7-80be8186dbf1){target="_blank"}                                                                                              |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 30     | Residuals and Plots                                  | -   READ:                                                                                                                                                                                                                    | -   GPset 30 |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 7 Linear regression with a single predictor from *Introduction to Modern Statistics (2e)*                                                                                                                    |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Sections 7.1.3, 7.2.4, and 7.2.5                                                                                                                                                                                 |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Sections 7.3 and 7.4                                                                                                                                                                                             |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Review the rest of the chapter from Lesson 29 reading as well                                                                                                                                                    |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 30](https://notebooklm.google.com/notebook/21876e79-e810-4c85-9aed-21adc8b527e2){target="_blank"}                                                                                              |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 31     | Train-Test Paradigm                                  | -   No assigned reading for Lesson 31                                                                                                                                                                                        | -   GPset 31 | -   Project Individual Task #3                                                                                                                                                                    |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   No reading guide for Lesson 31                                                                                                                                                                                           |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 32     | Multiple Regression (parallel slopes)                | -   READ:                                                                                                                                                                                                                    | -   GPset 32 | -   HW7                                                                                                                                                                                           |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 8 Linear regression with multiple predictors from *Introduction to Modern Statistics (2e)*                                                                                                                   |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Feel free to review Section 7.2.6 as well                                                                                                                                                                        |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   [Chapter 6 Multiple Regression from *ModernDive*](https://moderndive.com/v2/multiple-regression.html#multiple-regression){target="_blank"} (beginning of the chapter through Section 6.1.4)                          |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Pay special attention to Section 6.1.3 Model without interactions                                                                                                                                                |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 32](https://notebooklm.google.com/notebook/558a91f4-ad3c-43be-898a-5be8f71e3fce){target="_blank"}                                                                                              |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 33     | Multiple Regression (interaction), Simpson's paradox | -   READ:                                                                                                                                                                                                                    | -   GPset 33 |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   [Chapter 6 Multiple Regression from *ModernDive*](https://moderndive.com/v2/multiple-regression.html#multiple-regression){target="_blank"} (beginning of the chapter through Section 6.1.4)                          |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Pay special attention to Section 6.1.2 Model with interactions                                                                                                                                                   |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 3 Applications: Data from *Introduction to Modern Statistics (2e)*                                                                                                                                           |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 33](https://notebooklm.google.com/notebook/fe2919a4-12c7-47de-bfc5-0f73f45c6593){target="_blank"}                                                                                              |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 34     | Interpretation of Regression Tables                  | -   READ:                                                                                                                                                                                                                    | -   GPset 34 |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 24 Inference for linear regression with a single predictor from *Introduction to Modern Statistics (2e)*                                                                                                     |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 25 Inference for linear regression with multiple predictors from *Introduction to Modern Statistics (2e)*                                                                                                    |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Beginning of the chapter through Section 25.2                                                                                                                                                                    |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 34](https://notebooklm.google.com/notebook/a4c77a5e-ba44-420a-b3c7-f6541e81b284){target="_blank"}                                                                                              |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 35     | Multiple testing, p-hacking                          | -   READ:                                                                                                                                                                                                                    | -   GPset 35 | -   Project Group Task #3                                                                                                                                                                         |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   [Multiple Comparisons](https://www.biostathandbook.com/multiplecomparisons.html) from the *Handbook of Biological Statistics*                                                                                        |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   The section on Post-hoc testing in [this interactive tutorial](https://openintro.shinyapps.io/ims-05-infer-08/#section-post-hoc-testing)                                                                             |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   A quick definition of the [Bonferroni Correction](https://mathworld.wolfram.com/BonferroniCorrection.html) from Wolfram MathWorld                                                                                    |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Lies, Damn Lies, and Statistics - [a video explaining p-hacking](https://www.youtube.com/watch?v=Et9pORQHR2A) (watch the beginning through 10:52; stop when we transitions to talking about the Python code example) |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   OPTIONAL, if you're able to access this website from USAFA: [How do you know a paper is legit?](https://callingbullshit.org/tools/tools_legit.html) from *Calling Bullshit*                                          |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 35](https://notebooklm.google.com/notebook/9b682fdf-8953-4dc5-a2f5-b1bd502ef81a){target="_blank"}                                                                                              |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 36     | Central Limit Theorem                                | -   READ:                                                                                                                                                                                                                    | -   GPset 36 |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 13 Inference with mathematical models from *Introduction to Modern Statistics (2e)*                                                                                                                          |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Read Section 13.1 Central Limit Theorem                                                                                                                                                                          |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 19 Inference for a single mean from *Introduction to Modern Statistics (2e)*                                                                                                                                 |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Read Section 19.2 Mathematical model for a mean                                                                                                                                                                  |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Watch the [Bunnies and Dragons](https://youtu.be/jvoxEYmQHNM?si=iQUveQq9KxD7D5nk){target="_blank"} video                                                                                                             |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 36](https://notebooklm.google.com/notebook/179fb909-e21d-44de-abef-da761dacfb32){target="_blank"}                                                                                              |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 37     | t-tests                                              | -   READ:                                                                                                                                                                                                                    | -   GPset 37 | -   HW8                                                                                                                                                                                           |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 19 Inference for a single mean from *Introduction to Modern Statistics (2e)*                                                                                                                                 |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Review (from last lesson) Section 19.2 Mathematical model for a mean (especially 19.2.4 and 19.2.5)                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 20 Inference for comparing two independent means from *Introduction to Modern Statistics (2e)*                                                                                                               |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Section 20.3 Mathematical model for testing the difference in means                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Section 20.4 Mathematical model for estimating the difference in means                                                                                                                                           |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 16 Inference for a single proportion from *Introduction to Modern Statistics (2e)*                                                                                                                           |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Section 16.2 Mathematical model for a proportion                                                                                                                                                                 |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   Chapter 17 Inference for comparing two proportions from *Introduction to Modern Statistics (2e)*                                                                                                                     |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |         -   Section 17.3 Mathematical model for the difference in proportions                                                                                                                                                |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 37](https://notebooklm.google.com/notebook/b62f48c8-1c1e-4bf4-9e7d-26d4196d5d95)                                                                                                               |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 38     | GR4                                                  | Study! Practice!                                                                                                                                                                                                             | Relax!       |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 39     | ANOVA                                                | -   READ:                                                                                                                                                                                                                    | -   GPset 39 | -   [Course Participation form](https://forms.office.com/pages/responsepage.aspx?id=Bgq4einwwEWE0X2tGc48Ycp0mrZy4gRImknnfxDjZ-ZURE9WVE5BRk9TMkxMM1o1VVUyNlVNN1VBSi4u&route=shorturl)              |
|        |                                                      |                                                                                                                                                                                                                              |              | -   Project Group Task #4 - Final Submission                                                                                                                                                      |
|        |                                                      |     -   Chapter 22 Inference for comparing many means from *Introduction to Modern Statistics (2e)*                                                                                                                          |              | -   [Feedback to Group Project Members form](https://forms.office.com/Pages/ResponsePage.aspx?id=Bgq4einwwEWE0X2tGc48Ycp0mrZy4gRImknnfxDjZ-ZUQVUyR0wyWkEyUzEyWFFJQzFGTlhUUFpMMy4u) (opens 19 Nov) |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 39](https://notebooklm.google.com/notebook/23181388-f7ad-4050-ab94-4adeb7af485a)                                                                                                               |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 40     | Chi-squared tests                                    | -   READ:                                                                                                                                                                                                                    | -   GPset 40 | -   [Feedback to Fellow Statistics form](https://forms.office.com/r/UFqBD0Y3nT){target="_blank"} (opens 19 Nov)                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              | -   Strengths Activity #2                                                                                                                                                                         |
|        |                                                      |     -   Chapter 18 Inference for two-way tables from *Introduction to Modern Statistics (2e)*                                                                                                                                |              | -   [Post-course AI questionnaire](https://forms.office.com/pages/responsepage.aspx?id=Bgq4einwwEWE0X2tGc48Ycp0mrZy4gRImknnfxDjZ-ZUNzZMN09FSkQxSUhXNko3WUROQkQzNks5WC4u&route=shorturl)           |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      |     -   [Interactive tutorial](https://openintro.shinyapps.io/ims-05-infer-04/) on Chi-square goodness-of-fit tests                                                                                                          |              |                                                                                                                                                                                                   |
|        |                                                      |                                                                                                                                                                                                                              |              |                                                                                                                                                                                                   |
|        |                                                      | -   [Reading Guide for Lesson 40](https://notebooklm.google.com/notebook/8bd7de0c-d2d3-4fe8-9edc-6d0d34b428b0)                                                                                                               |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|        |                                                      | FINAL EXAM                                                                                                                                                                                                                   |              |                                                                                                                                                                                                   |
+--------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
