<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>FAQs – Data-Driven Statistics with AI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-fad5ab29a14bbe0a7a7d29177f3f13bb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data-Driven Statistics with AI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About this course</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./schedule.html"> 
<span class="menu-text">Course schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./course_project.html"> 
<span class="menu-text">Course project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./faqs.html" aria-current="page"> 
<span class="menu-text">FAQs</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="">
            Source Code
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="">
            Report a Bug
            </a>
          </li>
      </ul>
    </div>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#positive-comments" id="toc-positive-comments" class="nav-link active" data-scroll-target="#positive-comments"><strong>Positive Comments</strong></a></li>
  <li><a href="#grading-system-challenges" id="toc-grading-system-challenges" class="nav-link" data-scroll-target="#grading-system-challenges"><strong>Grading System Challenges</strong></a>
  <ul class="collapse">
  <li><a href="#standards-based-grading" id="toc-standards-based-grading" class="nav-link" data-scroll-target="#standards-based-grading"><strong>Standards-based grading</strong></a></li>
  <li><a href="#subjectivity-of-grades" id="toc-subjectivity-of-grades" class="nav-link" data-scroll-target="#subjectivity-of-grades"><strong>Subjectivity of grades</strong></a></li>
  <li><a href="#why-its-beneficial-to-you" id="toc-why-its-beneficial-to-you" class="nav-link" data-scroll-target="#why-its-beneficial-to-you"><strong>Why It’s Beneficial to You</strong></a></li>
  <li><a href="#understanding-the-proficiency-levels" id="toc-understanding-the-proficiency-levels" class="nav-link" data-scroll-target="#understanding-the-proficiency-levels"><strong>Understanding the Proficiency Levels</strong></a></li>
  <li><a href="#tracking-your-grades" id="toc-tracking-your-grades" class="nav-link" data-scroll-target="#tracking-your-grades"><strong>Tracking Your Grades</strong></a></li>
  <li><a href="#grades-going-into-the-final-exam" id="toc-grades-going-into-the-final-exam" class="nav-link" data-scroll-target="#grades-going-into-the-final-exam"><strong>Grades going into the Final Exam</strong></a></li>
  <li><a href="#final-grades-in-the-course" id="toc-final-grades-in-the-course" class="nav-link" data-scroll-target="#final-grades-in-the-course"><strong>Final Grades in the Course</strong></a></li>
  <li><a href="#grading-consistency" id="toc-grading-consistency" class="nav-link" data-scroll-target="#grading-consistency"><strong>Grading Consistency</strong></a></li>
  </ul></li>
  <li><a href="#workload-and-difficulty-of-the-course" id="toc-workload-and-difficulty-of-the-course" class="nav-link" data-scroll-target="#workload-and-difficulty-of-the-course"><strong>Workload and Difficulty of the course</strong></a>
  <ul class="collapse">
  <li><a href="#daily-battle-rhythm-of-the-course" id="toc-daily-battle-rhythm-of-the-course" class="nav-link" data-scroll-target="#daily-battle-rhythm-of-the-course"><strong>Daily Battle Rhythm of the course</strong></a></li>
  <li><a href="#non-math-penalties-grading-for-terminology" id="toc-non-math-penalties-grading-for-terminology" class="nav-link" data-scroll-target="#non-math-penalties-grading-for-terminology"><strong>Non-math penalties / grading for terminology</strong></a></li>
  <li><a href="#comparisons-to-current-versions-of-math-300356377" id="toc-comparisons-to-current-versions-of-math-300356377" class="nav-link" data-scroll-target="#comparisons-to-current-versions-of-math-300356377"><strong>Comparisons to current versions of Math 300/356/377</strong></a></li>
  </ul></li>
  <li><a href="#experimental-nature-and-uncertainty-around-the-course" id="toc-experimental-nature-and-uncertainty-around-the-course" class="nav-link" data-scroll-target="#experimental-nature-and-uncertainty-around-the-course"><strong>Experimental Nature and Uncertainty around the course</strong></a>
  <ul class="collapse">
  <li><a href="#is-this-a-new-way-of-teachinggrading" id="toc-is-this-a-new-way-of-teachinggrading" class="nav-link" data-scroll-target="#is-this-a-new-way-of-teachinggrading"><strong>Is this a new way of teaching/grading?</strong></a></li>
  </ul></li>
  <li><a href="#course-organization-and-structure" id="toc-course-organization-and-structure" class="nav-link" data-scroll-target="#course-organization-and-structure"><strong>Course Organization and Structure</strong></a>
  <ul class="collapse">
  <li><a href="#organization-of-the-course" id="toc-organization-of-the-course" class="nav-link" data-scroll-target="#organization-of-the-course"><strong>Organization of the course</strong></a></li>
  <li><a href="#platforms-used-in-the-course" id="toc-platforms-used-in-the-course" class="nav-link" data-scroll-target="#platforms-used-in-the-course"><strong>Platforms used in the course</strong></a></li>
  <li><a href="#studying-for-grs" id="toc-studying-for-grs" class="nav-link" data-scroll-target="#studying-for-grs"><strong>Studying for GRs</strong></a></li>
  </ul></li>
  <li><a href="#technology-and-tools-codingai" id="toc-technology-and-tools-codingai" class="nav-link" data-scroll-target="#technology-and-tools-codingai"><strong>Technology and Tools (Coding/AI)</strong></a>
  <ul class="collapse">
  <li><a href="#computing-tools" id="toc-computing-tools" class="nav-link" data-scroll-target="#computing-tools"><strong>Computing tools</strong></a></li>
  <li><a href="#genai-tools" id="toc-genai-tools" class="nav-link" data-scroll-target="#genai-tools"><strong>GenAI tools</strong></a></li>
  <li><a href="#documentation-statements" id="toc-documentation-statements" class="nav-link" data-scroll-target="#documentation-statements"><strong>Documentation Statements</strong></a></li>
  </ul></li>
  <li><a href="#concern-from-math-377-students" id="toc-concern-from-math-377-students" class="nav-link" data-scroll-target="#concern-from-math-377-students"><strong>Concern from Math 377 students</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">FAQs</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This page will contain answers to Frequently Asked Questions. Use the Table of Contents links in the sidebar to quickly move to a specific question/topic.</p>
<p>&nbsp;</p>
<p>Many of you expressed excitement for the course, and shared tips from friends/peers on how to be successful in the course.</p>
<section id="positive-comments" class="level2">
<h2 class="anchored" data-anchor-id="positive-comments"><strong>Positive Comments</strong></h2>
<blockquote class="blockquote">
<ul>
<li><p>“I’m also skeptical of cadet cynicism affecting how people communicate the reality of this course, as I have on multiple occasions loved courses which others told me were terrible. I’m excited for the class overall and curious to see for myself what the grading system ends up being like”</p></li>
<li><p>“interesting because it incorporates AI in a modern way”</p></li>
<li><p>“the way posit cloud operated was very cool and intuitive”</p></li>
<li><p>ability to “validate’ the final is a nice change”.</p></li>
<li><p>“very excited to try a different layout to a course”</p></li>
<li><p>“excited because its new”</p></li>
<li><p>“not too bad as long as students keep up with readings and spend sufficient time reviewing material each day”</p></li>
<li><p>“extremely helpful for the world around us”</p></li>
<li><p>“as long as I complete my assignments I can pass the class”</p></li>
<li><p>“I am excited to be in the class and have a positive mindset towards it”</p></li>
<li><p>“I haven’t heard anything about it, going to just see how it goes for myself”</p></li>
</ul>
</blockquote>
<p>About 13% of the cadets in the course haven’t heard much about Math Z yet, or are “excited” and feeling “positive” about the coming semester, the content of the course, or the move away from traditional points.</p>
<p>&nbsp;</p>
<p>There were also some shared concerns.</p>
</section>
<section id="grading-system-challenges" class="level2">
<h2 class="anchored" data-anchor-id="grading-system-challenges"><strong>Grading System Challenges</strong></h2>
<blockquote class="blockquote">
<p>This is by far the most frequently mentioned concern. Students have heard that the grading system is confusing, maybe frustrating, and subjective. Many reported hearing it was difficult to understand how to earn good grades (one even said “everyone left with poor grades”) and felt there was “no way to know what grades or levels of understanding correlated to each medal”. Some students heard that there was a lack of consistency in the grading, with “similar answers” earning a range of grades, and some heard it’s difficult to track your letter grade throughout the course.</p>
</blockquote>
<section id="standards-based-grading" class="level3">
<h3 class="anchored" data-anchor-id="standards-based-grading"><strong>Standards-based grading</strong></h3>
<p>Standards-based grading is about measuring your learning against clear, pre-defined standards rather than just adding up points. Instead of asking <em>“How many points have I earned?”</em> the question becomes <em>“How well have I mastered the skill or concept?” Y</em>our grade reflects what you can consistently do by the end of the course—skills and understanding you’ll actually use later.</p>
</section>
<section id="subjectivity-of-grades" class="level3">
<h3 class="anchored" data-anchor-id="subjectivity-of-grades"><strong>Subjectivity of grades</strong></h3>
<p>All grading is subjective. Even in points-based courses, your instructors subjectively decide whether to subtract 2 or 10 points for various mistakes.</p>
<p>Standards-based grading is typically more objective than traditional grading because everyone is measured against the same clear expectations, you get multiple opportunities to show what you know, and early mistakes don’t hold you back if you improve. It’s also easier for instructors to be consistent because they don’t have to figure out how many points to deduct. Instead, instructors are comparing your work to the proficiency levels defined in the course letter.</p>
</section>
<section id="why-its-beneficial-to-you" class="level3">
<h3 class="anchored" data-anchor-id="why-its-beneficial-to-you"><strong>Why It’s Beneficial to You</strong></h3>
<p>Standards-based grading places the focus on learning, not chasing points. Mistakes early on don’t doom you — you can show growth and still earn the highest marks. In the real world, no one cares if you once got 72% on a project — they care whether you can actually do the task now. Think about learning to drive — You don’t “average” your early driving mistakes with later successes to decide if you get your license. You keep practicing until you meet the standard for safe driving. That’s what standards-based grading does — it certifies that you’ve <em>actually mastered</em> the skills, not just accumulated enough points.</p>
</section>
<section id="understanding-the-proficiency-levels" class="level3">
<h3 class="anchored" data-anchor-id="understanding-the-proficiency-levels"><strong>Understanding the Proficiency Levels</strong></h3>
<p>This course previously used Gold, Silver, and Bronze to describe levels of achievement toward a given standard. We’ve renamed these proficiency levels to mirror one example of standards-based grading you’ll see in your careers as AF/SF officers. Federal employees are scored using standards-based grading on annual appraisals/performance plans, and pilots are scored using standards-based grading when qualifying on an aircraft.</p>
<p>When pilots want to qualify on an aircraft, they have to pass checkrides. Those checkrides are scored as Q1, Q2, or Q3. This semester, each standard in the course will be scored on a similar scale: Exceptionally Qualified, Q1, Q2, or Q3.</p>
<p>Based on Spring and Fall 2025 cadet feedback, we have redefined these proficiency levels too. Previously, your answer had to be perfect to earn a Q1. This semester, we recognize an instructor-level answer as Exceptionally Qualified and it is completely optional to attain that proficiency level. Your grade will be based on the amount of Q1, Q2, and Q3 standards you earn throughout the semester.</p>
<p>Based on previous cadet feedback, we include opportunities throughout the semester for you to see what a Q1, Q2, and Q3 response look like, prior to the GRs. We also encourage you to seek EI if you’re not sure what a Q1, Q2, or Q3 answer might look like for a certain type of question.</p>
</section>
<section id="tracking-your-grades" class="level3">
<h3 class="anchored" data-anchor-id="tracking-your-grades"><strong>Tracking Your Grades</strong></h3>
<p>We are adapting our grade tracker for the revised proficiency levels and will provide this as a resource to you, so that you can track your proficiency throughout the semester. Additionally, every cadet will receive a list of the core competency standards descriptions and their current proficiency levels for each GR, to help you in deciding which problems should be completed.</p>
</section>
<section id="grades-going-into-the-final-exam" class="level3">
<h3 class="anchored" data-anchor-id="grades-going-into-the-final-exam"><strong>Grades going into the Final Exam</strong></h3>
<p>Some cadets are entering the course with the belief that it is impossible to have a good grade before the final, that everyone walks into the final with an F. This is not quite the case, so let’s break this down a bit.</p>
<p>In a points-based course, the final exam must be worth at least 25% of the course grade. Let’s say you’re in a points-based course worth a total of 1000 points and the final is worth 250 of those points. Then everyone is walking into the final with a C (assuming you have all 750 points available so far) or lower.</p>
<p>What’s different about this course is that you will have seen and been tested on all 12 core competency standards prior to the final exam, and you’ll have another chance to attempt any of those 12 on the final exam. You can complete as much or as little of the final exam as you choose. Your final grade in this course is primarily based on your achievement of the 12 core competency standards. The professional development standards are largely completion based, and the application standards relate to homework, specialties, and the group project. These other categories can either “plus up” or “downgrade” your course grade, based on the amount of time and effort you put into the course assignments.</p>
<p>You will also have the grade tracker spreadsheet to track your proficiency levels throughout the semester, and you’re always able to chat with your instructor about where you stand in the course. We are also hopeful that the revised proficiency level descriptions will help you to better understand your grade in the course as we go.</p>
</section>
<section id="final-grades-in-the-course" class="level3">
<h3 class="anchored" data-anchor-id="final-grades-in-the-course"><strong>Final Grades in the Course</strong></h3>
<p>Some cadets heard the grading system was so harsh that “a lot of people ended up on academic probation at prog” or that “everyone left with poor grades” last semester. Neither of these statements is true.</p>
<p>In Spring 2025, 52% of the course (40/77 cadets) earned an A or B. In Fall 2025, 57% of the course (89/155 cadets) earned an A or B.</p>
<p>The grade distribution for the last two semesters of Math Z are shown below.</p>
<p><img src="images/course_grades_historical.png" class="img-fluid" width="590"></p>
<p>No one ended up on academic probation at prog solely due to Math Z last semester. The three Fs in Fall 2025 represent students who did not complete numerous assignments and/or did not take advantage of the opportunity to reattempt core competency standards throughout the semester.</p>
</section>
<section id="grading-consistency" class="level3">
<h3 class="anchored" data-anchor-id="grading-consistency"><strong>Grading Consistency</strong></h3>
<p>We did get feedback that some students compared answers on GR questions last semester and felt like the same answer resulted in different scores for different cadets. The main reason for this is differences in communication on GRs - communication is very important in statistics and there was a wide range of it on GRs. Apparent discrepancies in grades were almost always the result of correct/incorrect terminology or more/less effective communication in cadet answers.</p>
<p>&nbsp;</p>
</section>
</section>
<section id="workload-and-difficulty-of-the-course" class="level2">
<h2 class="anchored" data-anchor-id="workload-and-difficulty-of-the-course"><strong>Workload and Difficulty of the course</strong></h2>
<blockquote class="blockquote">
<p>While some heard the course was “not too bad”, a significant number of students heard the course is “very interesting and challenging” and “relatively difficult” with a “heavy course load”. Students expressed concern about “how much time outside of school this class will take up” and its overall workload. Additionally, one student wrote “I have heard that this classes medal system (or Q system), while less punishing, is way more time consuming than points based.”</p>
</blockquote>
<section id="daily-battle-rhythm-of-the-course" class="level3">
<h3 class="anchored" data-anchor-id="daily-battle-rhythm-of-the-course"><strong>Daily Battle Rhythm of the course</strong></h3>
<p>We are asking you to complete daily work (GPsets and reading guides) because it’s important for you to practice the skills in this course on a daily basis. Remember that all the daily work is graded on completion. We don’t expect you to understand all concepts or examples before class. We just expect that you complete the reading assignment, interact with the NotebookLM reading guide in some way, and bring questions to class.</p>
<p>This course is a 3-credit hour course. The expectation for all 3-credit hour courses is for every one hour class session, you should spend 2 hours outside of class working on that course. If you have Math Z on a Monday, Wednesday, Friday in a given week, that means you should expect to spend ~6 hours outside class on the course that week.</p>
</section>
<section id="non-math-penalties-grading-for-terminology" class="level3">
<h3 class="anchored" data-anchor-id="non-math-penalties-grading-for-terminology"><strong>Non-math penalties / grading for terminology</strong></h3>
<p>We did get feedback that some students compared answers on GR questions last semester and felt like the same answer resulted in different scores for different cadets. Apparent discrepancies in grades were almost always the result of correct/incorrect terminology or more/less effective communication in cadet answers. Some cadets even said it “seems to be like a pass-or-fail class, and if you don’t know certain terms verbatim, then you fail” or they heard “there were point deductions for non-math-related errors without much feedback”.</p>
<p>This is not a pass/fail class and we don’t expect you to know all the concepts verbatim. That being said, communication is very important in statistics. Much of the GRs are focused on concepts and communication rather than calculations or code. To achieve a certain core competency standard, you need to be able to correctly implement and communicate about a particular topic. Also, there are three things we expect you to know “word-for-word” in this class by the end of the semester, but we’ll footstomp those A LOT so you know what to expect.</p>
</section>
<section id="comparisons-to-current-versions-of-math-300356377" class="level3">
<h3 class="anchored" data-anchor-id="comparisons-to-current-versions-of-math-300356377"><strong>Comparisons to current versions of Math 300/356/377</strong></h3>
<p>The current versions of Math 300, Math 356, and Math 377 cover the same four blocks of content that we’ll cover this semester. All three courses use R/RStudio in the Posit Cloud environment, and all three courses emphasize simulation-based inference over more traditional methods like using t- and Z-tables.</p>
<p>This is not a ‘harder’ version of Math 300 nor is it an ‘easier’ version of Math 356, but we recognize that some of you have heard “it’s much more difficult to earn a good grade in comparison to ‘regular’ stats”. The main differences in Math 300, Math 356, and Math 377 were in the depth of content. This course combines those three populations (and cadets who would have previously taken BehSci 332) and makes adjustments as appropriate.</p>
<p>The final GPA for the DFMS statistics courses for the last two semesters are shown below:</p>
<table class="caption-top table">
<caption>&nbsp;</caption>
<thead>
<tr class="header">
<th>Course</th>
<th>Final GPA in Spring 2025</th>
<th>Final GPA in Fall 2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Math Z</td>
<td>2.89</td>
<td>2.81</td>
</tr>
<tr class="even">
<td>Math 300 (regular)</td>
<td>2.67</td>
<td>2.95</td>
</tr>
<tr class="odd">
<td>Math 356 (regular)</td>
<td>3.04</td>
<td>3.04</td>
</tr>
<tr class="even">
<td>Math 377 (regular, Fall 2024 for comparison)</td>
<td></td>
<td>2.96</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="experimental-nature-and-uncertainty-around-the-course" class="level2">
<h2 class="anchored" data-anchor-id="experimental-nature-and-uncertainty-around-the-course"><strong>Experimental Nature and Uncertainty around the course</strong></h2>
<blockquote class="blockquote">
<p>The course’s experimental nature itself is a source of concern, as it’s “intimidating to take an experimental course because the class might still change and develop which can make it stressful”. Students are “concerned for the experimental portion” and nervous about being guinea pigs for a “new way of teaching and grading”. A student expressed curiosity as to “why the 300, 356 and 377 were so similar in the first place that they could be combined”.</p>
</blockquote>
<p>This course is no longer experimental! There has been a push for the USAFA core curriculum to provide a common experience for cadets, no matter their major, and the Air Force and Space Force have clearly expressed a need for greater data acumen among all officers in recent years. This course has been approved by all DF departments and is soon-to-be-approved by the Academy Board as the single core statistics/data science course for cadets from all majors starting in Fall 2026.</p>
<p>That being said, “experimental” or “Z” courses can definitely seem intimidating at first, but we’ve put a lot of thought into this course. The course will not be changing while you take it this semester, but we do welcome your feedback as we continue to develop this course for future semesters.</p>
<section id="is-this-a-new-way-of-teachinggrading" class="level3">
<h3 class="anchored" data-anchor-id="is-this-a-new-way-of-teachinggrading"><strong>Is this a new way of teaching/grading?</strong></h3>
<p>This is not a new way of teaching or grading. The field of statistics education has been moving toward simulation-based statistics and emphasizing the use of technology and data in introductory statistics courses for the last 15 years.</p>
<p>Standards-based grading is not used widely at USAFA, but it has been mainstream in higher education for more than 10 years and there is extensive research about its benefits for students.</p>
<p>&nbsp;</p>
</section>
</section>
<section id="course-organization-and-structure" class="level2">
<h2 class="anchored" data-anchor-id="course-organization-and-structure"><strong>Course Organization and Structure</strong></h2>
<blockquote class="blockquote">
<p>Students reported the course being “unorganized and ran confusingly”. There’s concern about managing “so many platforms (Posit Cloud, R, NotebookLM, GenAI, Teams, Blackboard, GradeScope)”. Questions were raised about how to “study for a GR / Final and finding resources to study from”.</p>
</blockquote>
<section id="organization-of-the-course" class="level3">
<h3 class="anchored" data-anchor-id="organization-of-the-course"><strong>Organization of the course</strong></h3>
<p>To be honest, this course was unorganized and somewhat confusing for the first iteration in Spring 2025. A lot of this came from the effects of the stress and churn of the spring semester on civilian faculty and it being the first time the course ran. We have done a lot of work since last spring semester to simplify and organize components of this course and improve our communication wherever possible.</p>
</section>
<section id="platforms-used-in-the-course" class="level3">
<h3 class="anchored" data-anchor-id="platforms-used-in-the-course"><strong>Platforms used in the course</strong></h3>
<p>We will do our very best to help you manage the different platforms in the course. Our daily work is going to be in Posit Cloud. That is where you will use R/RStudio, so that is a single platform. All graded work will be submitted in Gradescope. There are many GenAI tools out there, but we’re going to emphasize NotebookLM this semester. You are welcome to use other tools as you are comfortable. Course communication will be in Teams. We will only use Blackboard for submitting prog and final grades, so you do not need to interact with Blackboard in this course.</p>
</section>
<section id="studying-for-grs" class="level3">
<h3 class="anchored" data-anchor-id="studying-for-grs"><strong>Studying for GRs</strong></h3>
<p>We’re confident that past GR questions are available to you in the Cadet Wing, so those problems are a good resource to study for GRs. The daily practice problems will turn into graded homework problems, and those are a great way to study for GRs as well. Additionally, we encourage the use of GenAI tools to create your own practice problems/examples when studying for GRs. You should provide an example problem wherever possible, but GenAI tools can personalize practice problems based on the lesson or course learning objectives, based on the core competency standards descriptions, or based on your own interests.</p>
<p>We recommend the following when prompting GenAI for practice problems. A strong prompt includes the following four elements:</p>
<ul>
<li><p>Role: Who should the GenAI tool act as? (e.g., a statistics instructor, a STEM tutor, a commander)</p></li>
<li><p>Task: What do you want the GenAI tool to do? Clear, specific instructions for what you want it to do</p></li>
<li><p>Output: What should the response look like? Format, structure, tone, number of problems, with or without solutions. This is a great place to provide an example from our GPset or from the reading (e.g., please provide practice problems similar to this one from my notetaker).</p></li>
<li><p>Context: What background does the GenAI tool need? Provide background materials (assignment instructions, rubric, this student is a Biology major, etc.)</p></li>
<li><p>Pro Tip: Before submitting your full prompt, ask the AI: <em>“What else do you need to know to complete this task effectively?”</em> Then revise your prompt accordingly.</p></li>
</ul>
<p>&nbsp;</p>
</section>
</section>
<section id="technology-and-tools-codingai" class="level2">
<h2 class="anchored" data-anchor-id="technology-and-tools-codingai"><strong>Technology and Tools (Coding/AI)</strong></h2>
<blockquote class="blockquote">
<p>A common theme is the integration of coding and artificial intelligence. Students are concerned about “working with some artificial intelligence that may be unfamiliar” and that there is “a lot of coding involved”. Many expressed discomfort with or a “difficult” learning curve for RStudio, as they “have not used it before this class” or needed to remember how to use it.</p>
</blockquote>
<p>This is not a coding class. You will be expected to use code on homeworks and the project, but we encourage you to use your resources (code provided in class, Google, Stack Overflow, GenAI tools like ChatGPT, etc.). We will always provide scaffolded code the first time we introduce you to a coding skill in R. We will never ask you to generate code from scratch in a timed environment (GRs) and we do not expect you to memorize code for this course.</p>
<section id="computing-tools" class="level3">
<h3 class="anchored" data-anchor-id="computing-tools"><strong>Computing tools</strong></h3>
<p>We are utilizing computing tools like Posit Cloud (R/RStudio) as a resource. Modern statistics cannot be separated from technology, and trust us - you don’t want to run these models or create visualizations by hand. While we acknowledge there can be a learning curve with RStudio/Posit Cloud, we will provide you with what you need when you need it (in regards to using Posit Cloud). We also put out some supplemental resources for those interested - see the RStudio folder under the Files tab in our course team.</p>
</section>
<section id="genai-tools" class="level3">
<h3 class="anchored" data-anchor-id="genai-tools"><strong>GenAI tools</strong></h3>
<p>Being able to use GenAI tools such as NotebookLM, ChatGPT, and other platforms is an essential skill for future AF/SF officers and anyone entering the job market today. In fact, Secretary Hegseth put out a release about GenAI.mil, saying, “I expect every member of the Department to log in, learn it, and incorporate it into your workflows immediately. AI should be in your battle rhythm every single day. It should be your teammate. By mastering this tool, we will outpace our adversaries. The power is now in your hands.”</p>
<p>We will not be grading you on any work that depends on GenAI tools. For the reading guides, we’re requiring you to interact with NotebookLM in some way, and we provide prompts to get you started. This is our way of trying to train you in responsible use of the tool and we’ll continue to provide examples and prompts throughout the semester.</p>
</section>
<section id="documentation-statements" class="level3">
<h3 class="anchored" data-anchor-id="documentation-statements"><strong>Documentation Statements</strong></h3>
<p>Some students have said “I am concerned with documentation because it is really lengthy and I fear I could make a mistake and miss something.” Please be assured that we approach GenAI usage and documentation as skills that you need to develop. We aim to help you grow in the responsible and proficient use of GenAI tools this semester.</p>
<p>Also, remember that if your instructor suspects you utilized GenAI tools without co-creating or with insufficient documentation, they will meet with you first to discuss and find ways to improve your usage and/or documentation. You may be asked to redo any graded work as deemed appropriate by your instructor and/or the course director. If there are recurrent issues related to GenAI usage or documentation, it may result in initiation of the honor process and/or an academic penalty.</p>
<p>&nbsp;</p>
</section>
</section>
<section id="concern-from-math-377-students" class="level2">
<h2 class="anchored" data-anchor-id="concern-from-math-377-students"><strong>Concern from Math 377 students</strong></h2>
<blockquote class="blockquote">
<p>Some of the 377 students have heard that Math 377 is called “Hell Stats” and they are nervous for the course. A significant concern among students in the experimental class is whether they “won’t be as prepared for 378 next semester” in terms of “the level of difficulty of using the content,” even if “the content is pretty much the same”. Math 377 students are “hoping to still get the same information as we would have if we had taken the regular course while also learning about it in a more manageable format” in the experimental class.</p>
</blockquote>
<p>All Math 377 students (Math/Applied Math, Data Science, and Operations Research majors) were enrolled in the Math 300Z/356Z/377Z course in Fall 2025 due to staffing in DFMS this year. The Math Z course will fulfill the core requirement for statistical reasoning that was previously filled by Math 300/356/377 or BehSci 332.</p>
<p>Math Z will also count as the prerequisite for Math 378 Applied Statistical Modeling, for any students required to take or interested in taking that course. We can assure you that this course will prepare you for Math 378 - Dr.&nbsp;Hitt has been the course director of Math 377/378 for the past four years, so you’re in good hands!</p>
<p>The primary difference between Math 377 and this experimental course is that we’ve removed some of the advanced probability topics. These topics are not necessary for Math 378 and many statisticians don’t see those topics until graduate school. Some of these advanced probability topics will be available to you as one of four specialties that you will choose as part of the Application standards. All DF departments are aware of this change, and we are working with some of them to prepare major-specific specialties in the Math Z course.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>